name: PyLint

on:
  push:
    branches:
      - 'main'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
          python-version: 3.11

    - name: Install required system packages
      run: |
          sudo apt-get update --fix-missing
          sudo apt-get install -y wget bzip2 ca-certificates curl git build-essential manpages-dev
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*

    - name: Copy requirements file
      run: |
          cp envs/pip/requirements.txt .
          cp envs/conda/environment.yml .

    - name: Install dependencies
      run: |
          $CONDA/bin/conda env update --file environment.yml
          $CONDA/bin/conda init bash
          
    - name: Install Swabber Python packages
      run: |
            source $CONDA/bin/activate swabber
            pip install --no-cache-dir --upgrade pip
            pip install --no-cache-dir -r requirements.txt 

    - name: Run PyTest
      run: |
        source $CONDA/bin/activate swabber
        PYTHONPATH=src/. pylint $(git ls-files '*.py' ':!:src/examples/*') --fail-under=5